name: LunaticStorage
version: '${project.version}'
main: de.janschuri.lunaticstorage.LunaticStorage
api-version: '1.19'

commands:
  storage:
    description: Open storage command
    usage: /storage
depend:
  - LunaticLib