name: LunaticStorage
version: '${project.version}'
main: de.janschuri.lunaticStorages.LunaticStorage
api-version: '1.20'

commands:
  storage:
    description: Open storage command
    usage: /storage
softdepend:
  - WorldGuard